import { requireProfile } from '@/lib/auth';
import { formatDate } from '@/lib/date';
import { MetricForm } from '@/components/forms/simple-record-forms';
import { Card } from '@/components/ui/card';
import { PageHeader } from '@/components/layout/page-header';
import { UrlTabs } from '@/components/ui/url-tabs';
import { EmptyState } from '@/components/ui/feedback';

export default async function ProgressPage({searchParams}:{searchParams:Promise<{tab?:string}>}){const params=await searchParams;const tab=['resumen','registrar','historial'].includes(params.tab??'')?params.tab!:'resumen';const{supabase,userId}=await requireProfile();const{data}=await supabase.from('body_metrics').select('*').eq('profile_id',userId).order('recorded_on',{ascending:false}).limit(30);const latest=data?.[0];const tabs=[{value:'resumen',label:'Resumen',href:'/progreso?tab=resumen'},{value:'registrar',label:'Registrar',href:'/progreso?tab=registrar'},{value:'historial',label:'Historial',href:'/progreso?tab=historial',count:data?.length??0}];return <section className="space-y-7"><PageHeader eyebrow="Mediciones manuales" title="Progreso registrado" description="Sólo verás valores que tú agregaste. GLM no completa, predice ni altera mediciones."/><UrlTabs items={tabs} active={tab}/>{tab==='registrar'?<Card><h2 className="font-display mb-5 text-2xl">Registrar medición</h2><MetricForm/></Card>:tab==='historial'?data?.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.map((item)=><Card key={item.id}><p className="text-xs font-bold uppercase tracking-wide text-primary">{formatDate(item.recorded_on)}</p><p className="font-display mt-3 text-3xl">{item.weight_kg?`${item.weight_kg} kg`:'Sin peso'}</p><p className="mt-2 text-sm text-muted-foreground">{item.height_cm?`Altura ${item.height_cm} cm`:''}{item.waist_cm?` · Cintura ${item.waist_cm} cm`:''}</p></Card>)}</div>:<EmptyState title="Sin mediciones" description="Registra peso, altura o cintura cuando tú decidas medirlos."/>:<div className="grid gap-4 sm:grid-cols-3"><MetricSummary label="Peso más reciente" value={latest?.weight_kg?`${latest.weight_kg} kg`:'Sin registro'}/><MetricSummary label="Altura más reciente" value={latest?.height_cm?`${latest.height_cm} cm`:'Sin registro'}/><MetricSummary label="Cintura más reciente" value={latest?.waist_cm?`${latest.waist_cm} cm`:'Sin registro'}/><div className="sm:col-span-3"><p className="text-sm leading-6 text-muted-foreground">Estas tarjetas no calculan tendencias ni predicciones. Cada valor proviene de una medición manual.</p></div></div>}</section>}
function MetricSummary({label,value}:{label:string;value:string}){return <Card><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="font-display mt-3 text-3xl">{value}</p></Card>}
